version: '3.1'
services:
  elasticsearch:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300